spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: "validate"
      dialect: "PostgreSQLDialect"
      default_schema: "internet_store"
    show-sql: true

  datasource:
    initialization-mode: always
    url: "jdbc:postgresql://localhost:5432/internet_store"
    username: "admin"
    password: "admin"

  flyway:
    url: "jdbc:postgresql://localhost:5432/internet_store?ssl=false"
    user: "admin"
    password: "admin"
    locations: "classpath:/db/migration"

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  freemarker:
    templateLoaderPath:
      - "classpath:/static/template/ftl/"

---

spring:
  config:
    activate:
      on-profile: dev
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId:
#    user:
#      name: "user"
#      password: "user"
#      role: "user"

name: dev-spring
environment: develop
enabled: true
key: "Secret_Key"



server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: prod
name: prod-spring
environment: develop
enabled: false

server:
  port: 8095